# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_pk', models.TextField(verbose_name='object ID')),
                ('archive', models.CharField(choices=[('archive.org', 'archive.org')], db_index=True, default='archive.org', max_length=1000)),
                ('url', models.URLField(max_length=1000)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_memento', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'ordering': ('-timestamp',),
                'get_latest_by': 'timestamp',
            },
        ),
    ]
