# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('publication_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-publication_date',),
                'get_latest_by': 'publication_date',
            },
        ),
    ]
